### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by PabloBrianese** [llimllib/bloomfilter-tutorial#13]
At line 326 of [index](https://github.com/llimllib/bloomfilter-tutorial/blob/master/index.html), we can find a [broken link](http://blip.tv/pycon-us-videos-2009-2010-2011/pycon-2011-handling-ridiculous-amounts-of-data-with-probabilistic-data-structures-4899047).
It could be replaced by [this one](https://pyvideo.org/pycon-us-2011/pycon-2011--handling-ridiculous-amounts-of-data-w.html).

Thank you for the page, I didn't know about Bloom filters <3

**Comment by jg23497** [comment]
Hi @PabloBrianese,

I fixed this and the other broken links in PR https://github.com/llimllib/bloomfilter-tutorial/pull/14, which has now been merged, so I suggest this issue is now closed.

And I agree, it's a very useful resource for those wanting to understand Bloom filters.

Thanks.
