### ISSUE TITLE
Set used for illustration purpose is allowing duplicates

### ISSUE THREAD

**Issue by gansai** [llimllib/bloomfilter-tutorial#3]
Hi, I am new to bloom filter. I was going through the tutorial.
In the illustration part, I tried adding elements to the set.
I assume that the definition of a set is that it does not allow duplicate elements.

But, I could add in such a way as below:-
Your set: [baba, sairam, take, baba, dingding, dingding, baba]

**Comment by llimllib** [comment]
A bloom filter only tells you if an element may or may not be in the set, so it allows duplicates.
