### ISSUE TITLE
Cross site scripting in entering a new string 

### ISSUE THREAD

**Issue by makash** [llimllib/bloomfilter-tutorial#5]
When we add a new strings and click on add to bloom filter we can inject HTML and JavaScript.

By adding `<h1 onmousever=alert('xss')>XSS</h1>` we can cause a cross site scripting issue.

While it isn't a big deal for a static HTML page, it is never a good idea to have a XSS vulnerability on your primary domain. 

<img width="1139" alt="screen shot 2015-08-28 at 10 58 58" src="https://cloud.githubusercontent.com/assets/343204/9539768/30c1df12-4d74-11e5-9fc9-e9fc6a6a1c9e.png">

If you prefer I can fork and do a pull request as well. Honestly don't mean to be a bother but just wanted to let you know.

**Comment by llimllib** [comment]
Excellent point, and thanks so much for reporting it.

ec606c2 fixes it, right? [`.text(str)`](https://api.jquery.com/text/) escapes the string before inserting it.

**Comment by makash** [comment]
Yes sir, that works just fine. Great!

**Comment by llimllib** [comment]
![](https://giphy.com/gifs/animatedtext-transparent-yellow-wordart-aKjnUBa0nSGn6)
