### ISSUE TITLE
Bloom Filter Explanation

### ISSUE THREAD

**Issue by priyakhokher** [llimllib/bloomfilter-tutorial#8]
Hi @llimllib
great explanation.

Though I was wondering in the case below:
![image](https://cloud.githubusercontent.com/assets/13968539/26167794/b073de92-3aec-11e7-8447-b872b223b26e.png)

when string 'pppp' is not there it still says it's there that means it has false negatives.
Why so ?

**Comment by llimllib** [comment]
That's a false positive, not a false negative; the bloom filter said "yes that element might be in the set" but it is not. bits 4 and 3 are set, so the bloom filter reports that `pppp` may have been seen already; the text should explain why that is.

**Comment by priyakhokher** [comment]
Hmm so shouldn't it say "Definitely not"
If I check for an element like 'a' it says no. Infact it says for 'pp' as well - for 'pppp' it's says maybe which is similar to it saying for 'ad'

**Comment by llimllib** [comment]
> Hmm so shouldn't it say "Definitely not"

no, maybe is the correct answer

> If I check for an element like 'a' it says no. Infact it says for 'pp' as well

yes, both of those hash to values that are not set in the bit vector, so it can definitively say "no".

> for 'pppp' it's says maybe 

yes, that hashes to values that are set in the bit vector, so all a bloom filter can tell you is that it may be in the set

> which is similar to it saying for 'ad'

yes, 'ad' hashes to values that are set in the bit vector, so a bloom filter can tell you that it may be in the set.

From the article:

> a Bloom filter is a probabilistic data structure: it tells us that the element either definitely is not in the set or may be in the set.

**Comment by priyakhokher** [comment]
Anyway I really liked the explanation a lot !
